title: Max Saber, DHA, MSHI, FACHDM
tagline: Director, Enterprise Applications, Adjunct Professor of Healthcare Business
url: https://maxsaber.com
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Max Saber, DHA, MSHI, FACHDM
  url: https://maxsaber.com
  email: max@maxsaber.com

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-admin
  #- jekyll/twemoji
  - jekyll-tagging-related_posts

include:
 - .well-known

port: 5001

# Google Analytics Tag
google_analytics: G-JB5BFVF5QL

jekyll_admin:
  homepage: "pages"

collections:
  courses:
    # Create non-dated collection for courses, dir: _course
    permalink: /:collection/:slug
    output: true
  posts:
    permalink: /blog/:categories/:year/:slug
    output: true

defaults:
  - scope:
      # For all posts in _course folder, apply default values
      path: _courses
      type: courses
    values:
      layout: course
      categories: courses