# frozen_string_literal: true

# capitalizewords / https://github.com/jasoncomes/Capitalize-Words-Liquid-Filter
# Takes a string or variable and capitalizes the first letter of every word.
# {{ string | capitalizewords }}

module CapitalizeWords
  # Transforms a list of words into a new list where each word is capitalized.
  # 
  # @param words [Array] sequence of words to be capitalized.
  # 
  # @returns [String] a space-separated list of capitalized words, generated by splitting
  # the input string into individual words and capitalizing each one.
  def capitalizewords(words)
    words.to_s.split(' ').map(&:capitalize).join(' ')
  end
end

Liquid::Template.register_filter(CapitalizeWords)